status = [
    "fuzz",
    "test (stable, default)",
    "clippy",
    "fmt",
    "test (stable, std proto-ipv4)",
    "test (stable, std medium-ethernet phy-raw_socket proto-ipv6 socket-udp)",
    "test (stable, std medium-ethernet phy-tuntap_interface proto-ipv6 socket-udp)",
    "test (stable, std medium-ethernet proto-ipv4 proto-igmp socket-raw)",
    "test (stable, std medium-ethernet proto-ipv4 socket-udp socket-tcp)",
    "test (stable, std medium-ethernet proto-ipv4 proto-dhcpv4 socket-udp)",
    "test (stable, std medium-ethernet proto-ipv6 socket-udp)",
    "test (stable, std medium-ethernet proto-ipv6 socket-tcp)",
    "test (stable, std medium-ethernet proto-ipv4 socket-icmp socket-tcp)",
    "test (stable, std medium-ethernet proto-ipv6 socket-icmp socket-tcp)",
    "test (stable, std medium-ethernet proto-ipv4 proto-ipv6 socket-raw socket-udp socket-tcp socket-i...",
    "test (1.53.0, default)",
    "test (1.53.0, std proto-ipv4)",
    "test (1.53.0, std medium-ethernet phy-raw_socket proto-ipv6 socket-udp)",
    "test (1.53.0, std medium-ethernet phy-tuntap_interface proto-ipv6 socket-udp)",
    "test (1.53.0, std medium-ethernet proto-ipv4 proto-igmp socket-raw)",
    "test (1.53.0, std medium-ethernet proto-ipv4 socket-udp socket-tcp)",
    "test (1.53.0, std medium-ethernet proto-ipv4 proto-dhcpv4 socket-udp)",
    "test (1.53.0, std medium-ethernet proto-ipv6 socket-udp)",
    "test (1.53.0, std medium-ethernet proto-ipv6 socket-tcp)",
    "test (1.53.0, std medium-ethernet proto-ipv4 socket-icmp socket-tcp)",
    "test (1.53.0, std medium-ethernet proto-ipv6 socket-icmp socket-tcp)",
    "test (1.53.0, std medium-ethernet proto-ipv4 proto-ipv6 socket-raw socket-udp socket-tcp socket-i...",
    "test (nightly, default)",
    "test (nightly, std proto-ipv4)",
    "test (nightly, std medium-ethernet phy-raw_socket proto-ipv6 socket-udp)",
    "test (nightly, std medium-ethernet phy-tuntap_interface proto-ipv6 socket-udp)",
    "test (nightly, std medium-ethernet proto-ipv4 proto-igmp socket-raw)",
    "test (nightly, std medium-ethernet proto-ipv4 socket-udp socket-tcp)",
    "test (nightly, std medium-ethernet proto-ipv4 proto-dhcpv4 socket-udp)",
    "test (nightly, std medium-ethernet proto-ipv6 socket-udp)",
    "test (nightly, std medium-ethernet proto-ipv6 socket-tcp)",
    "test (nightly, std medium-ethernet proto-ipv4 socket-icmp socket-tcp)",
    "test (nightly, std medium-ethernet proto-ipv6 socket-icmp socket-tcp)",
    "test (nightly, std medium-ethernet proto-ipv4 proto-ipv6 socket-raw socket-udp socket-tcp socket-...",
    "test (nightly, alloc medium-ethernet proto-ipv4 proto-ipv6 socket-raw socket-udp socket-tcp socke...",
    "check (stable, medium-ip medium-ethernet proto-ipv6 proto-ipv6 proto-igmp proto-dhcpv4 socket-raw...",
    "check (stable, defmt defmt-trace medium-ip medium-ethernet proto-ipv6 proto-ipv6 proto-igmp proto...",
    "check (1.53.0, medium-ip medium-ethernet proto-ipv6 proto-ipv6 proto-igmp proto-dhcpv4 socket-raw...",
    "check (1.53.0, defmt defmt-trace medium-ip medium-ethernet proto-ipv6 proto-ipv6 proto-igmp proto...",
    "check (nightly, medium-ip medium-ethernet proto-ipv6 proto-ipv6 proto-igmp proto-dhcpv4 socket-ra...",
    "check (nightly, defmt defmt-trace medium-ip medium-ethernet proto-ipv6 proto-ipv6 proto-igmp prot...",
]
